import { Product } from './Product';

  export const PRODUCTS: Product[] = [
      { id: 1, name: 'Narty', src: '/assets/img/skis/big_a48c82e99ec94d4d967ff56b84e2bb50.jpg', price: 99.99, size: 170,
        info: 'Narty idealne do ...'},
      { id: 2, name: 'Narty biegowe', src: '/assets/img/skis/meskie-narty-biegowe.jpg', price: 109.99, size: 180,
        info: 'Narty idealne do ...'},
      { id: 3, name: 'Narty atomic redster', src: '/assets/img/skis/narty-atomic-redster-doubledack-xt.jpg', price: 89.99, size: 180,
        info: 'Narty idealne do ...'},
      { id: 4, name: 'Narty biegowe fischer', src: '/assets/img/skis/narty-biegowki-klasyk-fischer_n43616_fibre_crown.jpg', price: 129.99, size: 190,
        info: 'Narty idealne do ...'},
      { id: 5, name: 'Narty local hero', src: '/assets/img/skis/narty-local-hero-jr.jpg', price: 109.99, size: 170,
        info: 'Narty idealne do ...'},
      { id: 6, name: 'Narty salomon x-race', src: '/assets/img/skis/narty-salomon-x-race-sw.jpg', price: 139.99, size: 160,
        info: 'Narty idealne do ...'},
      { id: 7, name: 'Narty', src: '/assets/img/skis/narty-volkl-nanuq.jpg', price: 109.99, size: 165,
        info: 'Narty idealne do ...'},
      { id: 8, name: 'Narty biegowe rekreacyjne', src: '/assets/img/skis/nartybiegowe_rekreacyjne.jpg', price: 119.99, size: 175,
        info: 'Narty idealne do ...'},
      { id: 9, name: 'Gogle rekreacyjne', src: '/assets/img/gogles/gogle1.jpg', price: 109.99, size: 160,
        info: 'Gogle idealne do ...'},
      { id: 10, name: 'Gogle profesjonalne', src: '/assets/img/gogles/gogle2.jpg', price: 89.99, size: 165,
        info: 'Gogle idealne do ...'},
      { id: 11, name: 'Gogle turystyczne', src: '/assets/img/gogles/gogle3.jpg', price: 69.99, size: 175,
        info: 'Gogle idealne do ...'},
      { id: 12, name: 'Gogle amatorskie', src: '/assets/img/gogles/gogle4.jpg', price: 59.99, size: 180,
        info: 'Gogle idealne do ...'},
      { id: 13, name: 'Kijki rekreacyjne', src: '/assets/img/kijki/kijki1.jpg', price: 99.99, size: 160,
        info: 'Kijki idealne do ...'},
      { id: 14, name: 'Kijki profesjonalne', src: '/assets/img/kijki/kijki2.jpg', price: 89.99, size: 165,
        info: 'Kijki idealne do ...'},
      { id: 15, name: 'Kijki turystyczne', src: '/assets/img/kijki/kijki3.jpg', price: 109.99, size: 175,
        info: 'Kijki idealne do ...'},
      { id: 16, name: 'Kijki amatorskie', src: '/assets/img/kijki/kijki4.jpg', price: 59.99, size: 180,
        info: 'Kijki idealne do ...'},
      { id: 17, name: 'Kask rekreacyjny', src: '/assets/img/kaski/kask1.jpg', price: 199.99, size: 180,
        info: 'Kask idealny do ...'},
      { id: 18, name: 'Kask profesjonalny', src: '/assets/img/kaski/kask2.jpg', price: 189.99, size: 175,
        info: 'Kask idealny do ...'},
      { id: 19, name: 'Kask turystyczny', src: '/assets/img/kaski/kask3.jpg', price: 149.99, size: 165,
        info: 'Kask idealny do ...'},
      { id: 20, name: 'Kask amatorski', src: '/assets/img/kaski/kask4.jpg', price: 129.99, size: 188,
        info: 'Kask idealny do ...'}
  ]
